# .github/workflows/ci.yml
name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBT_POSTGRES_PW: ${{ secrets.DBT_POSTGRES_PW }}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DBT_POSTGRES_PW }}
          POSTGRES_DB: dbt_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Install dependencies
        run: dbt deps

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          quant:
            target: ci
            outputs:
              ci:
                type: postgres
                host: localhost
                user: postgres
                password: ${DBT_POSTGRES_PW}
                port: 5432
                dbname: dbt_ci
                schema: quant
                threads: 4
          EOF


      - name: Debug connection
        run: dbt debug

      - name: Run dbt build
        run: dbt build